### ISSUE TITLE
osascript-based interfaces are very energy inefficient

### ISSUE THREAD

**Issue by blahsd** [blahsd/snwe#21]
All the scripts that rely on constant polling through osascript (iTunes, Spotify, taskbar) are relatively resource heavy.

**Comment by CarlosEvo** [comment]
osascript can use javascript, would it reduce the load?

**Comment by blahsd** [comment]
@CarlosEvo could you provide an example? It might be interesting

**Comment by CarlosEvo** [comment]
I am not a developer, this is the example I found, [since you mentioned itunes on reddit](https://github.com/mischah/itunes-remote)

Maybe it will save some energy compared to calling on the shell to run AppleScript, but I would assume it would cost the same. Using precompiled binaries CLI tools might help, but I Do not know any.

**Comment by blahsd** [comment]
Unfortunately the package you linked seems to be using osascript as well, so ultimately it's going to be the same load on the machine. Thanks tho, it was a good shot. I'm now trying to do that balancing of resource and responsiveness that I was talking about on reddit. If you'd like to help testing give me a shout

**Comment by blahsd** [comment]
<img width="1920" alt="screenshot 2018-06-06 17 53 27" src="https://user-images.githubusercontent.com/7347353/41050141-d347c92e-69b2-11e8-948f-e205d4c88750.png">

snwe w/o active task monitor now has a lower average energy impact than the desktop dropbox integration. This is a solved issue in my book.
